### ISSUE TITLE
User Story: View individual product details

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/ecommerce#10]
EPIC 1: UX/UI

As a **Customer**, I can **View information about an individual product**, so that **I can decide whether or not I want to buy it** 

**Tasks:**
- [x] Create urls and views to render a page that shows information about an individual product
- [x] Create user interface to display the relevant information

**Acceptance Criteria:**
- Product page needs to display: 
  - [x] product name
  - [x]  photo 
  - [x] brand 
  - [x] price
  - [x] add to basket button
  - [x] quantity selector
  - [x] ingredients
  - [x] description
  - [x] brand info
  - [x] nutrition info

- [x] Ingredients, description, brand and nutrition are in accordions set to be not expanded by default
