### ISSUE TITLE
User Story: View list of products by brand

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/ecommerce#11]
EPIC 1: UX/UI

As a **Customer**, I can **View products by one or more specific brands**, so that **I can see which products from brands I like are available to buy** 

**Tasks:**
- [x] Create urls and views to create a page to display products by brand
- [x] Add to page html template to display brand information 
- [x] Add to page html template to display list of products belonging to a brand

**Acceptance Criteria:**
- [x] Page displays a list of products by a given brand, displayed in product cards (as per the category page)
- [x] Page also displays the brand's name and description info
