### ISSUE TITLE
User Story: Set up user authentication

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/ecommerce#12]
EPIC 2: User Authentication

As a **Customer**, I can **Sign up for an account**, so that **I can save my details for next time** 

**Tasks:**
- [x] Set up django-allauth to handle authentication
- [x] Create urls/views/templates for a 'my account' section
- Sections to include:
Musts:
  - [x] Saved addresses, with functionality to add, edit and remove addresses (customer will be able to select an address at the checkout stage, with one already saved as the default address)
  - [x] Order history, which displays details of previous orders to the customer
Shoulds:
  - [x] Change/add email address (allauth provides a template for this) 
Coulds:
- [ ] Favourites: enable list of favourited products
- [ ] Loyalty points: functionality so that customer can see how many loyalty points they have gained

**Acceptance Criteria:**
- [x] Customer can log in and out of their account
- [x] Customer can add, edit and remove their shipping addresses 
- [x] Customer can add, edit and remove their email addresses

**Comment by charleymroberts** [comment]
Just 'order history' left to do from the 'musts' list, which needs to wait until the checkout functionality has been implemented

**Comment by charleymroberts** [comment]
All complete apart from Loyalty Points and Favourites, which will now be implemented in a future iteration
