### ISSUE TITLE
User Story: Add individual product info

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/ecommerce#13]
EPIC 3: CRUD

As a **Retailer**, I can **Add new products and their details individually**, so that **Product information can be stored in the database and displayed to my customers on the webshop** 

**Tasks:**
- [x] Create ProductForm
- [x] Create HTML form for retailer to fill in 

**Acceptance Criteria:**
- [x] Retailer can add product details for all model fields
- [x] Form updates the information in the database and on the webshop
