### ISSUE TITLE
User Story: View items in basket

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/ecommerce#14]
EPIC 4: Basket/Purchasing

As a **Customer**, I can **View the items in my basket**, so that **I can review my order and see the total cost** 

**Tasks:**
- [x] Add table showing each order item's name, quantity, subtotal, quantity adjustor, delete item button  
- [x] Calculate and display total cost of all items
- [x] Calculate if the order qualifies for free delivery, display delivery charge if not, and how much the customer needs to spend to qualify for free delivery

**Acceptance Criteria:**
- [x] Customer can see items they have put in the basket, edit quantities and delete items
- [x] Customer can see subtotal for each item line and the total of all items
- [x] Customer can see delivery cost, and if applicable how close they are to the free delivery threshold
