### ISSUE TITLE
User Story: Sort product lists or search results

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/ecommerce#16]
EPIC 1: UX/UI

As a **Customer**, I can **Sort lists of products by name or price**, so that **I can more easily find what I'm looking for** 

**Tasks:**
- [x] Add 'sort by' menu to category pages and search results
- [x] Add functionality to order products A-Z, Z-A, price low-high and price high-low

**Acceptance Criteria:**
- [x] Customers can order product lists  A-Z, Z-A, price low-high and price high-low using the drop down menu button
