### ISSUE TITLE
User Story: Action confirmation

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/ecommerce#17]
EPIC 1: UX/UI

As a **Customer or Retailer **, I can **see confirmation of my actions**, so that **I can see they've worked successfully** 

**Tasks:**
- [x] Add 'messages' to base template
- [x]  Add messages into view functions for add product to basket, update quantity, remove product from basket (customers), 
- [x]  Add messages into view functions for add new product, edit product, delete product (retailers)
- [x] If time, convert these messages to use Toasts

**Acceptance Criteria:**
- [x] Customers are displayed confirmation messages for add product to basket, update quantity, remove product from basket
- [x] Retailers are displayed confirmation messages for add new product, edit product, delete product
- [x] Toasts are used to display messages instead of default template messages fields (Should)

**Comment by charleymroberts** [comment]
Have used bootstrap_messages (using django_bootstrap5) to display message popups rather than Toasts
