### ISSUE TITLE
User Story: Retailer user account

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/ecommerce#18]
EPIC 2: User Authentication and 3: CRUD

As a **Retailer**, I can **log in to an admin user account**, so that **I can add and edit products without having to log in to the Django admin panel** 

**Tasks:**
- [x] Set up user authentication
- [x] Add retailer dashboard with CRUD functionality for products and brands
- [x] Add permission_required to ensure that these can only be accessed by the store owner

**Acceptance Criteria:**
- [x] Store owner can log in and out of their account
- [x] Store owner can see whether or not they are currently logged in
- [x] Store owner can add, edit and delete products and brands (but not delete brands if they still have products associated with them)
- [x] Users who do not have superuser permissions cannot access this functionality

**Comment by charleymroberts** [comment]
(Have not included custom functionality to delete brands, but store owner could do this via the admin panel if wished)
