### ISSUE TITLE
User Story: Edit individual product info

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/ecommerce#19]
EPIC 3: CRUD

As a **Retailer**, I can **Edit products individually that are already in the products database**, so that **I can keep their information up to date for my customers** 

**Tasks:**
- [x] Create 'edit product' form that recalls the product data and allows the user to edit and save it
- [x] Add 'edit this product' button to individual product pages which links to the 'edit product' form
- [x] Add 'edit product' form to the retailer admin dashboard

**Acceptance Criteria:**
- [x] Retailer can edit and save details of products that already exist in the database
- [x] Edit product form is accessible from a custom admin panel and from the individual product pages
