### ISSUE TITLE
User Story: Delete individual products

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/ecommerce#20]
EPIC 3: CRUD

As a **Retailer**, I can **Delete products from the database**, so that **My products list is kept up to date** 

**Tasks:**
- [x] Create 'delete product' button that deletes individual products
- [x] Implement an 'are you sure' confirmation message before the delete action takes place
- [x] Add permission_required decorators to prevent unauthorised users accessing delete functionality

**Acceptance Criteria:**
- [x] Retailer can delete individual products from the database
- [x] Retailer needs to click on a further confirmation message before deletion takes place
- [x] Users without superuser permissions cannot delete products
