### ISSUE TITLE
User Story: Switch products between published and draft

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/ecommerce#21]
EPIC 3: CRUD

As a **Retailer**, I can **Switch individual products between 'published' and 'draft'**, so that **I can remove them from my public products list without having to delete the product information (e.g. for seasonal products I might want to sell again next year)** 

**Tasks:**
- [ ] Implement a setting to switch products between being publicly visible on the webshop and not being publicly visible (with default being that they are visible)

**Acceptance Criteria:**
- [ ] Retailer can choose whether or not an individual product appears on their webshop
- [ ] Product details are still stored in the database when not being displayed publicly on the webshop

**Comment by charleymroberts** [comment]
This item will be held back for a future iteration due to reaching the end of the current sprint.
