### ISSUE TITLE
User Story: Links to social media

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/ecommerce#23]
EPIC 5: Marketing

As a **Retailer**, I can **Display links to my social media pages on my webshop**, so that **Customers follow me on social media and view future marketing posts** 

**Tasks:**
- [x] Add icons for social media pages to the base template footer
- [x] Implement links to social media that open in a new tab

**Acceptance Criteria:**
- [x] Icons are present in the footer
- [x] Links to social media pages link to the correct place
- [x] Links open in a new tab
- [x] Icons include labels for screen readers
