### ISSUE TITLE
User Story: Mailing list signup

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/ecommerce#24]
EPIC 5: Marketing

As a **Retailer**, I can **Encourage customers to sign up for my email list**, so that **I can send them marketing emails that they have chosen to receive** 

**Tasks:**
- [x] Sign up for Mailchimp
- [x] Embed their mailing list sign up code in the footer of the base template
- [x] Check that sign up works

**Acceptance Criteria:**
- [x] Sign up form displays in the website footer
- [x] The mailing list receives new email addresses that are submitted via the form
