### ISSUE TITLE
User Story: Other products you might like

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/ecommerce#25]
EPIC 5: Marketing

As a **Retailer**, I can **Suggest additional products to the customer that they might then choose to buy, 
based on the products they are currently looking at**, so that **The customers who visit my site buy more products than they might otherwise have done** 

**Tasks:**
- [x] Create 'products you might be interested in' section at the bottom of the individual product page
- [x] Populate this with a template to display four products chosen at random from the same category as the current product

**Acceptance Criteria:**
- [x] Four products are displayed at the bottom of the product page
- [x] Products are from the same category as the product the user is currently viewing
- [x] A different combination of four new products appears at random when the product page is loaded
