### ISSUE TITLE
User Story: View basket and total cost

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/ecommerce#26]
EPIC 4: Basket/Purchasing

As a **Customer**, I can **View the contents of my basket and the total price of all the items**, so that **I can check which items I have added and find out the total price of my shop so far** 

**Tasks:**
- [x] Implement functionality to add products to basket
- [x] Add functions to calculate the cost of each order line (if customer has more than one of the same item) and the total of all basket items so far, which increments as customer adds items
- [x] Add a message to tell the customer how much more they need to spend to get free delivery
- [x] Display confirmation message when customer adds items to the basket or edits the quantity of an item

**Acceptance Criteria:**
- [x] Items are added successfully to the basket
- [x] Messages are displayed to confirm adding items to the basket or updating their quantity
- [x] Basket displays subtotals for each line and total for the entire basket so far
- [x] Subtotals and total are updated as the customer adds or removes items
