### ISSUE TITLE
User Story: Guest checkout

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/ecommerce#30]
EPIC 2: User Authentication

As a **Customer**, I can **Buy products without having to sign up for an account**, so that **I do not lose patience and go and buy my items elsewhere** 

**Tasks:**
- [x] Allow the purchasing process to work without restricting essential parts of it to logged-in users only
- [x] Include a link on the checkout page inviting users to create an account so that they can save their details for next time
- [x] Require customers to enter their name, email, address line one, town/city/area, and postcode on the checkout page so that the store owner has the details required to post their order and send a confirmation email
 
**Acceptance Criteria:**
- [x] Flow from arriving on the website to checking out all works without requiring login
- [x] Link present on the checkout page linking to the 'create an account' page
- [x] Required fields prompt the user to complete them before the checkout form will submit
