### ISSUE TITLE
User Story: Search box

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/ecommerce#31]
EPIC 1: UX/UI

As a **Customer**, I can **Search the whole site using a word or phrase**, so that **I can search the whole site using a word or phrase** 

**Tasks:**
- [x] Implement free text search functionality
- [x] Add a search box to the navbar

**Acceptance Criteria:**
- [x] Search box is present in the navbar
- [x] Accurate results appear related to the user's search
