### ISSUE TITLE
User Story: Implement the user interface based on the wireframe designs

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/ecommerce#7]
EPIC 1: UX/UI

As a **Customer**, I can **Easily find my way around an intuitive user interface**, so that **I can find the items I want to purchase** 

**Tasks:**
- [x] Create interface for home page
- [x] Create base template including header, navbar and footer to be used with all other templates
- [x] Create navbar using the product categories in the database
- [x] Create interface html template for a page that will display lists of products within categories
- [x] Create interface html template for a page showing details of each individual product
- [x] Create interface for a page showing information about each brand and listing all products by that brand
- [x] Create urls and views to implement the above pages
- [x] Create context file to allow navbar data to be visible across all apps within the site

**Acceptance Criteria:**
- User Interface exists (at least in outline form) for each of:
  - [x] Home page
  - [x] Base template / navbar
  - [x] Categories page
  - [x] Brand page
  - [x] Individual product page

- [x] Interface design for each of the above pages is responsive and displays correctly on browsers from 320px up to large desktop screen size
- [x] Semantic HTML and alt text (or emtpy alt tags when images are solely decorative) are in place
