### ISSUE TITLE
User Story: Implement styling for user interface

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/ecommerce#8]
EPIC 1: UX/UI

As a **Customer**, I can **Enjoy the experience of using an attractive, trustworthy-looking interface**, so that **I feel good about using the site and will be encouraged to make a purchase** 

**Tasks:**
- [x] Select and apply colour scheme
- [x] Select and apply fonts
- [x] Find/create and apply decorative images for the home page
- [x] Apply styling to other elements

**Acceptance Criteria:**
- [x] Consistent colour scheme in place throughout the site
- [x] Sufficient contrast between text and background fonts to be acceptable for accessibility (e.g. passes Lighthouse checks)
- [x] Consistent use of fonts in place throughout the site (no more than three different fonts in total)
- [x] Home page makes use of attractive images as a large banner across the top of the page 
- [x] Home page makes use of attractive images to illustrate each top-level product category
