### ISSUE TITLE
User Story: 'View products by category' pages

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/ecommerce#9]
EPIC 1: UX/UI

As a **Customer**, I can **View lists of products grouped together by category**, so that **I can see all the products of a particular type that are available to choose from** 

**Tasks:**
- [x] Create urls and views to create a page to display products by category
- [x] Create navigation helpers, e.g. breadcrumb menus, links from 'all products in this category' page to narrow the product list by subcategories
- [x] Create a 'sort by' menu to order product lists
- [x] Create a template using Bootstrap's 'Card' feature to display the details of individual products
- [x] Create a for loop so that each page displays the relevant products

**Acceptance Criteria:**
- [x] Page created that displays all the products in a top-level category (e.g. Chilled)
- [x] Page created that displays all the products in a subcategory (e.g. vegan cheese)
- [x] Subcategory page includes breadcrumbs menu showing its top level category
- [x] Top category page displays buttons across the top of the page with links to its subcategories
- [x] 'Sort by' menu orders products A-Z, Z-A, price low-high and price high-low
- Card needs to display:
  - [x] Product name (as link to individual product)
  - [x] Product category
  - [x] Product photo (as link to individual product)
  - [x] Price
  - [x] Brand
  - [x] 'Add to basket' button
